name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy lúc 0h UTC mỗi ngày (7h sáng giờ VN)

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update log file
        run: |
          echo "Hoạt động tự động lúc: $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "dodanghoana12017@gmail.com"
          git add log.txt
          git commit -m "Cập nhật log tự động ngày $(date)"
          git push