name: Random Quotes Commits

on:
  workflow_dispatch:  # Chạy thủ công để test

jobs:
  random-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test
        run: echo "Test chạy" >> test.txt
      - name: Commit
        run: |
          git config --local user.name "Test"
          git config --local user.email "test@example.com"
          git add test.txt
          git commit -m "Test commit"
          # Bỏ git push
